### ISSUE TITLE
Windows 10 April 2018 Update with high-dpi displays: RibbonButton dropdown items click events not firing.

### ISSUE THREAD

**Issue by Al-74** [RibbonWinForms/RibbonWinForms#10] opened 2018-05-14 09:41 UTC
This issue happens only on Windows 10 updated to April 2018 (version 1803). If you set the display scaling above 100% (i tried 150% and 200%), the click event does not fire when clicking items on dropdown RibbonButtons.
Note that scaling over 100% is the default in most high-dpi displays.

Debugging the issue I have discovered that the problem is related to FeedHookClick function on RibbonPopupManager class. This function checks if the mouse position is contained into the dropdown bounds.
While before April 2018 Update the mouse location passed as parameter is scaled accordingly with display scaling setting, on April 2018 the mouse location is the real one, related to the physical display resolution, not scaled.
If you set the display scaling at 100% the virtual ant the physical mouse coords are the same, so the issue does not happens.
On April 2018 Update when scaling over 100% the FeedHookClick function mouse position check fails because the (physical) mouse position is outside the (virtual) dropdown bounds, so the function returns false and no mousedown/click/ect. events are fired.

The mouse location passed to FeedHookClick function come from the windows message queue hooked with SetWindowsHookEx API (see GlobalHook class, InstallHook function). This means that Microsoft has changed some policies on passing these coords with April 2018 Update.
Can this be considered a bug from Microsoft? Maybe, i don't know. The problem is: how to fix the bug on the Ribbon? You could change the FeedHookClick function scaling correctly the mouse position before checking, but it will work only on April 2018 Update, not with prior versions.
Should you check the version of Windows and scaling before checking only if >= April 2018 Update?

Anyway, in the meantime i have modified the FeedHookClick function returning **ALWAYS** true, so the mouse events are always fired. I have made some tests and, for my situation, i have not found any negative side effects.

Somebody can say something more about this issue?

NOTE that maybe the problem could be the same of the issue #1 opened on 26 Nov 2017 by PietF

**Comment by adriancs2** [comment] 2018-05-21 01:47
You can commit the changes to the repository

**Comment by drony** [comment] 2018-05-23 18:59
yes same problem here. interestingly my office computer doesn't affected.

**Comment by PietF** [comment] 2018-05-27 18:30
AL-74
did yoy test clicking outside the ribbon yet?  I think the dropdown is going to stay open.
You can replace e.Location by using the GetCursorPos API for a better solution. 
GetCursorPos calculates the logical (scaled) location and that is just what we need.
As far as I can see you also have to alter HandleHookMouseDown in the Ribbon class for the same.

PietF

**Comment by Al-74** [comment] 2018-05-29 08:04
PietF
actually you are right, with my changes clicking outside the dropdown is going to stay open.
My doubt on correcting the problem re-calculating the mouse position (eg. using GetCursorPos API) is that it should be done only if windows is 1803 version, not for other versions.
Morover this new behavior of windows should also be a temporary bug, that could be corrected on a next windows update, sooner or later.

**Comment by RussKie** [comment] 2018-05-29 09:16
I think the change must be reverted because it breaks it for everyone.
A targeted (temporary?) fix may need to be applied for 1803.
It may or may not be fixed by MS.

**Comment by remyGrandry** [comment] 2018-05-30 13:17
I can confirm that issue too on these specs : 

- MacBook Pro 2016 15"
- Windows on virtual machine (Parallels Desktop with HiDPI ON)

Cliking on Combobox has no effect

**Comment by PietF** [comment] 2018-06-03 19:03
AL-74,
Using GetCursorPos calculates always the logical (scaled) location.
It also should work on older systems. (even when testing on my windows vista everything is okay) 
I don't see that this should break it for everyone, tempory bug or not.

PietF

**Comment by Al-74** [comment] 2018-06-13 13:20
PietF,
i have made some tests using GetCursorPos and actually it seems to work well in all situations.
adriancs2 I have created a pull request with the correct fix.
Thank you guys!

**Comment by DarkAnd** [comment] 2018-07-20 18:29
I use ribbon in my projects since 2014, never gave a problem, but now with the update of windows 10, it is giving that CLick problem, which has already been reported, would you just update the ribbon35 dll without having to redo the project?

I tried replacing the Ribon dll just by giving rename, but it did not work

**Comment by adriancs2** [comment] 2019-08-19 15:55
Hi, this problem is fixed in latest version. You may try the nuget version.
Guide: How to add ribbon library via Nuget:
https://github.com/RibbonWinForms/RibbonWinForms/wiki

**Closed by adriancs2** 2019-08-19 15:55 UTC
