### ISSUE TITLE
So, Windows 10

### ISSUE THREAD

**Issue by mason-bially** [RibbonWinForms/RibbonWinForms#8] opened 2018-04-06 02:22 UTC
Currently there appears to be some issues with this library on windows 10 (weird border, blurry text, cut off elements, flickering).

![windows10](https://user-images.githubusercontent.com/1072924/38400687-2aa08a18-3906-11e8-99b6-04f82f0c31a4.PNG)

I'd be willing to work on a new "Office 2016" style (because I need it anyway) and to fix some of these bugs.

![office2016](https://upload.wikimedia.org/wikipedia/en/5/54/Microsoft_Office_2016_Screenshots.png)

If I can ask some questions, get feed back here, and make issues here I would be willing to contribute these changes back to the community. I'm just putting this out here to see if anyone is already doing it, or has any thoughts, or would like to help in anyway (so we can divvy up the work).

**Comment by C00lzer0** [comment] 2018-04-08 13:16
Not only that, in overflow mode the content of the popup looks weird too and the ribbon rendering is also not realy correct:
![image](https://user-images.githubusercontent.com/929700/38467973-d5326f74-3b3f-11e8-9982-3b464ffe6e08.png)

**Comment by adriancs2** [comment] 2018-04-09 00:59
Yupe, current Ribbon does not draw correctly in Windows 10. It requires a new approach, a new block of coding to draw accordingly for Win 10.

**Comment by adriancs2** [comment] 2018-04-13 02:25
Most of the senior team members of this project are either left the project or become inactivity, so can't help much to modify the code of the Ribbon to compatible with Windows 10.

**Comment by adriancs2** [comment] 2018-04-13 02:28
Hello mason-bially, I have invited you to the team. You can check your notification or email for the invitation link. You can commit code changes to the repository. Thanks for your contribution to the community.

**Comment by jaydfox77** [comment] 2018-10-23 17:09
I ran into that issue with the popup causing rendering issues.  Found the bug in RibbonPanel.cs, lines 444-446 in the version I downloaded.  It's inside the OnPaint event.  The fakePanel.SetOwner(Owner) call needs to be moved ABOVE the fakePanel.SetBounds(overflowBoundsBuffer) call.  The SetBounds method is referencing the Owner, which is null.  Reordering the calls fixes the issue.

> Not only that, in overflow mode the content of the popup looks weird too and the ribbon rendering is also not realy correct:
> ![image](https://user-images.githubusercontent.com/929700/38467973-d5326f74-3b3f-11e8-9982-3b464ffe6e08.png)

**Comment by adriancs2** [comment] 2018-10-24 13:56
Hi, jaydfox77, I have invited you as member of this project. You may check the invitation link in your message box. Then, you are welcome to commit the changes to improve this project. Thanks for your contribution.

**Comment by adriancs2** [comment] 2018-10-24 13:58
Hi, mason-bially, none of us is fixing this issue. You are welcome to go ahead to commit the fixes into the repository directly. Thanks.

**Comment by tajbender** [comment] 2019-07-13 20:00
@adriancs2: Adrian, I found this Component again, after it had been abandoned a few years ago. I'm happy to see it is alive again!

Just downloaded the binary releases and saw that there are still rendering issues in Windows 10. Is it just my machine, or are there still issues open; is anyone currently working on this, and if not, may I try to do my best to fix them?

But I would need some advice where to get started as I'm completely new to the project...

However, thanks in advance and for your work respectively 🥇

**Comment by adriancs2** [comment] 2019-07-15 05:23
@tajbender You may submit code fixes/patches by submitting a pull request

**Comment by tajbender** [comment] 2019-07-16 23:05
The text issues result from a erroneous "IsGlassEnabled"-property in WinAPI.cs:

>        public static bool IsGlassEnabled
>        {
>            get
>            {
>                //Check is windows vista
>                if (IsVista)        //         public static bool IsVista => IsWindows && Environment.OSVersion.Version.Major >= 6;
>                {
>                    //Check what DWM says about composition
>                    int enabled = 0;
>                    int response = DwmIsCompositionEnabled(ref enabled);
>
>                    return enabled > 0;
>                }
>
>                return false;
>            }
>        }
>

So as a result, the Vista Glass-renderer path is used all the time. Just commenting out the checks leads to clear text in Windows 10:

![RibbonWinForms_Win10_Text](https://user-images.githubusercontent.com/10961499/61335574-4882bb80-a82e-11e9-9eac-34a1222828f8.png)

As Windows 8 and above don't use glass effects, IMHO there shouldn't be implications if I fix this issue. Does everybody agree?

However, I cannot test Win Vista/7/8, as my machine only runs Win 10. Would be nice if someone could test the other OSes.

Then I would try to fix the caption bar issues itself...

**Comment by adriancs2** [comment] 2019-07-17 02:39
As a quick solution to having a second OS, you can try using VMware Workstation Player or VirtualBox to install win7. You can ignore the compatibility with Vista and Win 8. and finally you may submit a pull request for the code patches. We thank for the efforts and your contribution towards the community.

**Comment by tajbender** [comment] 2019-07-17 05:47
There is a lot more to do then that to get a clean code base; I just started converting

`Classes\WinApi.cs`

into UTF-8, cause it had the wrong encoding. That's why the file history is corrupted.

- I would suggest creating a branch for a new release, just to be sure to have the changes isolated from the existing codebase. Then I suggest to isolate the render paths into different classes, to gain:

1. Performance
2. Make further maintenance easier

- I would also refactor the examples, cause some are broken.
- I would refactor the precompiled binaries, installer, docs, etc., cause there are lots of minor issues I found. A refactoring would make it easier for other people to get in touch with the component. Finally, I suggest releasing a stable version via NuGet.

However, one person alone can't test all this things against WinVista/7/8/10, and all available Office Renderer. So, to make things easier it would be nice to get some stuff orchestrated by the project maintainer  ;)

It also would be nice if @harborsiem could contact me, since it seems he was the last person that made fundamental changes to the code.

**Comment by tajbender** [comment] 2019-07-17 20:04
@adriancs2: Are you okay with my ideas and suggestions? And would you assist me in testing and whenever I may have questions, and do the final code review?

**Comment by adriancs2** [comment] 2019-07-18 01:28
@tajbender Okay, I try my best to assist you :)

**Comment by mason-bially** [comment] 2019-07-18 18:40
I might also be able to do some testing or work. The project I was going to do this work for got scrapped for unrelated reasons, but some of the code using this ribbon still survives, but it was never worth it (and still isn't) to clean it up. But I'll see if I can contribute stuff (if at all).

**Comment by tajbender** [comment] 2019-07-19 05:17
@adriancs2, @mason-bially : Thank you so much for your feedback.

I'm not allowed to write to this repository, so I forked my own version here: https://github.com/tajbender/RibbonWinForms/commits/master

I'll try to make atomic commits, so the steps that will be made should be self-explanatory. Certainly everyone is welcome to take a look and contribute :wink:

There are still things that give me headache, e.g. why - and where - the window border itself is drawn; take a look at the top of the screenshot:

![RibbonWinForms_Win10_Top](https://user-images.githubusercontent.com/10961499/61510607-e2479580-a9f3-11e9-9aa6-60f0c923e0b6.png)

Perhaps someone of you has an idea, and can give me a hint where the 10 pixel at the top come from? (It's a Win 10 machine, so I don't think it's windows itself that draws that stuff in that style.)

Thanks in advance, and have a nice weekend. Take a look at the :full_moon: :new_moon:

**Comment by adriancs2** [comment] 2019-07-19 06:22
@tajbender Hi, I have invited you to join the developer team. You may visit this link to accept the invitation. After joined, you can submit code/write to the repository directly.

**Comment by tajbender** [comment] 2019-07-21 18:25
Thank you so much, @adriancs2 🥇 . I'll branch the repository, import my work made so far and give feedback as soon as I have a stable version.

I'm glad to be on board and hope to be of value for the project 👍

**Comment by tajbender** [comment] 2019-07-30 05:05
Sorry for being late, but last week it was way too hot here in Europe to do coding stuff 😬 

> ![RibbonWinForms_Win10_Top](https://user-images.githubusercontent.com/10961499/61510607-e2479580-a9f3-11e9-9aa6-60f0c923e0b6.png)
> 
> Perhaps someone of you has an idea, and can give me a hint where the 10 pixel at the top come from? (It's a Win 10 machine, so I don't think it's windows itself that draws that stuff in that style.)

First, to answer that, it's done in `RibbonFormHelper.PaintTitleBar()`.

I've pushed the changes I made so far into branch `Win10_Fixes_and_Refactoring`. Most of them are minor changes and Refactoring, including the Win10-RibbonTab-Text-Fix mentioned above.

For now, the problem is the title bar which is always drawn in the same color, regardless of form's activation state. But I'm working on that.

However, you are always welcome to test this stuff so far, especially on Windows < 10 😁 Thanks in advance!

**Comment by tajbender** [comment] 2019-08-01 04:09
@adriancs2: Could you give me a hint what the default behavior for the title bar under Windows < Win 8 is?

Is there any difference, i.e., is it drawn in different colour(s) when activated, in contrast to being drawn when the window is not activated? Could you perhaps provide an image of the difference?

As said, I only have a AMD Ryzen machine, which won't run Windows < 8 cleanly, or rather I'm still working on that. And I'm a little bit confused, cause what I've seen so far the title bar itself is drawn multiple times, in different layers over themselves so to say. This doesn't make it easier, to be honest 😭

**Comment by tajbender** [comment] 2019-08-01 04:50
> Is there any difference, i.e., is it drawn in different colour(s) when activated, in contrast to being drawn when the window is not activated? Could you perhaps provide an image of the difference?

Okay, I've found myself, it's another Colour. Now I've to found where this is done 😁

**Comment by tajbender** [comment] 2019-08-03 08:07
Hi, mates. Hi, @adriancs2,

after having a hard time doing these minor changes mentioned above, trying to fix the problems that followed that "simple" solution made my sick 💩 

Then, I thought why to reinvent the wheel when it perhaps would be very simple. So I just dropped a manifest file to the solution, added the dpi-awareness-flag; 

>`  <application xmlns="urn:schemas-microsoft-com:asm.v3">`
>`    <windowsSettings>`
>`      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>`
>`    </windowsSettings>`
>`  </application>`

and commented out a minor amount of code in `OnRenderRibbonTabText`, and voila:

![Ribbon - TextIssues with manifest_03-08-19](https://user-images.githubusercontent.com/10961499/62409025-9428b980-b5d1-11e9-91df-9f56dbc96165.png)

except some minor issues cause of miscalculated rendering space (which could be fixed soon I guess), it looks pretty nice.

The changes made, well, I just commented out the Glass-rendering stuff:

>                using (Brush b = new SolidBrush(GetTextColor(e.Tab.Enabled, e.Tab.Active ? ColorTable.TabActiveText : ColorTable.TabText)))
>                {
>                    //if (e.Ribbon.ActualBorderMode == RibbonWindowMode.NonClientAreaGlass)
>                    //{
>                    //    GraphicsPath p = new GraphicsPath();
>
>                    //    float emSize = e.Graphics.DpiY * e.Ribbon.RibbonTabFont.Size / 72;
>                    //    p.AddString(tabText, e.Ribbon.RibbonTabFont.FontFamily, 0, emSize, r, sf);
>
>                    //    SmoothingMode sbuff = e.Graphics.SmoothingMode;
>                    //    e.Graphics.SmoothingMode = SmoothingMode.HighQuality;
>                    //    e.Graphics.FillPath(b, p);
>                    //    e.Graphics.SmoothingMode = sbuff;
>                    //}
>                    //else
>                    //{
>                        e.Graphics.TextRenderingHint = TextRenderingHint.ClearTypeGridFit;
>                        e.Graphics.DrawString(tabText, e.Ribbon.RibbonTabFont, b, r, sf);
>                    //}
>                }  

The advantages should be obvious. As soon as we drop the `if (e.Ribbon.ActualBorderMode == RibbonWindowMode.NonClientAreaGlass)`, we would get a cleaner code base, the text issues should be fixed, and in the end, if I fix the form-border-color and the problems caused by the dpi-awareness-stuff, the component itself should be dpi-aware **and** ready for Win 10...

So, what do you think about?

@adriancs2: Could we exchange E-Mail-Addresses for easier correspondence in any form?

**Comment by adriancs2** [comment] 2019-08-03 08:52
@tajbender Sure, here is my email.
avoomj@yahoo.com

**Comment by adriancs2** [comment] 2019-08-19 15:58
Hi @tajbender , thanks for the fixes :)

**Closed by adriancs2** 2019-08-19 15:58 UTC
Labels: bug, enhancement
