### ISSUE TITLE
RibbonMouseSensor

### ISSUE THREAD

**Issue by lricx** [RibbonWinForms/RibbonWinForms#25] opened 2019-01-08 21:15 UTC
Hello,
I do not have any knowledge in English, excuse me for that.
I want to congratulate you on the excellent project and who is contributing to the improvements.
When trying out this project I intend to use it, I realized that when I dynamically create dropdown items and when too full popup panel appears and with that I can not move them with the mouse at all. Could anyone check this out on this project? Thank you all.
![testribbon](https://user-images.githubusercontent.com/46502769/50859166-c181f180-1379-11e9-8537-bfcea8ea20a3.png)

**Comment by adriancs2** [comment] 2019-08-19 15:03
I run a test and the problem is gone.
This problem has already fixed in new version.
You may try to use the nuget version.

Guide: How to Install via Nuget:
https://github.com/RibbonWinForms/RibbonWinForms/wiki

**Closed** 2019-08-19 15:03 UTC
