### ISSUE TITLE
when dropdown Orb, it fires a RibbonButton event 

### ISSUE THREAD

**Issue by juanlas17** [RibbonWinForms/RibbonWinForms#2] opened 2017-12-12 22:42 UTC
Hi, first, sorry, my English isn't that good, i don't speak them.

I found the problem when i click the Orb, then, the Ribbon Control fires a Click Event of the first RibbonButton added into the first panel of the first Tab.

Eg:

            private System.Windows.Forms.RibbonPanel rpEmisionComprobantes;
            this.rpEmisionComprobantes = new System.Windows.Forms.RibbonPanel();

            private System.Windows.Forms.RibbonButton rbFacturacion;
            this.rbFacturacion = new System.Windows.Forms.RibbonButton();

            this.rbFacturacion.Image = ((System.Drawing.Image)(resources.GetObject("rbFacturacion.Image")));
            this.rbFacturacion.LargeImage = ((System.Drawing.Image)(resources.GetObject("rbFacturacion.LargeImage")));
            this.rbFacturacion.MaxSizeMode = System.Windows.Forms.RibbonElementSizeMode.Medium;
            this.rbFacturacion.Name = "rbFacturacion";
            this.rbFacturacion.SmallImage = ((System.Drawing.Image) resources.GetObject("rbFacturacion.SmallImage")));
            this.rbFacturacion.Text = "Facturas";
            this.rbFacturacion.Click += new System.EventHandler(this.rbFacturacion_Click);

            this.rpEmisionComprobantes.Items.Add(this.rbFacturacion);

When i click the Orb, the ribbon fires rbFacturacion_Click event, and then DropDown the orb

Can u help me to solve this?

Thanks

Juan

**Comment by adriancs2** [comment] 2019-08-19 16:03
Hi, this problem is fixed in latest version. You may try the nuget version.
Guide: How to add ribbon library via Nuget:
https://github.com/RibbonWinForms/RibbonWinForms/wiki

Below is a sample project which shows that the problem is gone. You may have a look.
[WindowsFormsApp1.zip](https://github.com/RibbonWinForms/RibbonWinForms/files/3516651/WindowsFormsApp1.zip)

**Closed by adriancs2** 2019-08-19 16:03 UTC
